### ISSUE TITLE
RcppPlanc does not install on Linux with OpenBLAS and FlexiBLAS with cblas.h

### ISSUE THREAD

**Issue by fizwit** [welch-lab/RcppPlanc#9]
### How to reproduce
```
git clone git@github.com:welch-lab/RcppPlanc.git
R CMD INSTALL ./RcppPlanc
```

Gist of error log:  [gist](https://gist.github.com/fizwit/515d04095d76db006b6b0ac3af41ceef)

### Environment
```
R --version
R version 4.4.0 (2024-04-24) -- "Puppy Cup"
Copyright (C) 2024 The R Foundation for Statistical Computing
Platform: x86_64-pc-linux-gnu

cmake --version
cmake version 3.27.6

g++ --version
g++ (GCC) 13.2.0

uname -m
x86_64
```

### FlexiBLAS and OpenBLAS 
Both are in LD_LIBRARY_PATH 
```
/app/software/FlexiBLAS/3.3.1-GCC-13.2.0/lib
/app/software/OpenBLAS/0.3.24-GCC-13.2.0/lib
```

**Comment by theAeon** [comment]
Interesting edge case. Let me tweak that quickly.

**Comment by theAeon** [comment]
should be fixed in https://github.com/welch-lab/RcppPlanc/commit/7560174406c831cc35175e21f25c282395c87995

**Comment by theAeon** [comment]
wait, I may be stupid, hold on

**Comment by theAeon** [comment]
Turns out the actual issue is that I wasn't making sure that libblas was being used before running the check for whether libblas has libcblas symbols. Oops.

Also, checking cblas before flexiblas/cblas is wrong.
